services:
  db:
    image: postgres:16
    container_name: realworld_db
    restart: always
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realworld_api
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"
